version: "3.4"
services:
  tree:
    build:
      context: tree/.
    ports:
      - 80:4000
    networks:
      - default
  bamboo:
    build:
      context: bamboo/.
    environment:
      BAMBOO_SUBDOMAIN: stridenyc
      BAMBOO_API_KEY: API_KEY_GOES_HERE
    ports:
      - 4000:4000
    networks:
      - default
  sponsers:
    build:
      context: sponsers/.
    environment:
      DB: mongodb://sponsers_db/app
    ports:
      - 4001:4000
    depends_on:
      - sponsers_db
    networks:
      - default
  sponsers_db:
    image: mongo:latest
    networks:
      - default
networks:
  default:
    driver: bridge
