version: "3.4"
services:
  tree:
    build:
      context: tree/.
    ports:
      - 80:4000
    networks:
      - default
  bamboo:
    build:
      context: bamboo/.
    environment:
      BAMBOO_SUBDOMAIN: stridenyc
      BAMBOO_API_KEY: API_KEY_GOES_HERE
    ports:
      - 4000:4000
    networks:
      - default
  sponsors:
    build:
      context: sponsors/.
    environment:
      DB: mongodb://sponsors_db/app
    ports:
      - 4001:4000
    depends_on:
      - sponsors_db
    networks:
      - default
  sponsors_db:
    image: mongo:latest
    networks:
      - default
  seed:
    build: ./seed
    depends_on:
      - sponsors_db
    networks:
      - default
networks:
  default:
    driver: bridge
